log_root: 'logs'
seed: 999
lr: 2e-4
ebm_module: 'ebms.cnn_mlp'
conv_layers:
  - [4, 4, 4, 2, 1] # input_channels, output_channels, kernel_size, stride, padding
fc_layers:
  - [1024, 4096] # latent code 4x32x32
  - [4096, 1024]
  - [1024, 256]
  - [256, 64]
  - [64, 1]
sigma: 3e-2 # data noise
mcmc_noise: 1e-3 # sampling noise coefficient
n_iters: 10000
m: 64 # mini batch size
K: 30 # MCMC steps
step_size: 0.6
dataset_module: 'datasets.cifar10_256'
