log_root: 'logs'
seed: 999
lr: 1e-5
ebm_module: 'ebms.cnn_mlp' # TODO: can abstract this further
conv_layers: [] # no cnn
fc_layers:
  - [64, 128] # using 32by32 cifar 10, latent is 4, 4, 4, which is 64
  - [128, 256]
  - [256, 512]
  - [512, 256]
  - [256, 1]
sigma: 3e-2 # data noise
n_iters: 10000
m: 64 # mini batch size
K: 30 # MCMC steps
step_size: 0.3
dataset_module: 'datasets.cifar10_32'

