log_root: 'logs'
seed: 999
lr: 1e-5
ebm_module: 'ebms.cnn_mlp' # TODO: can abstract this further
conv_layers: [] # no cnn
fc_layers:
  - [64, 1000] # using 32by32 cifar 10, latent is 4, 4, 4, which is 64
  - [1000, 2000]
  - [2000, 200]
  - [200, 100]
  - [100, 1]
sigma: 3e-2 # data noise
n_iters: 20000
m: 64 # mini batch size
K: 100 # MCMC steps - TODO: lowered to 30 from 100
step_size: 0.6 # just a test 
dataset_module: 'datasets.cifar10_32'